-- megafunction wizard: %FFT v13.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			auk_dspip_r22sdf_top_fft_130
-- ============================================================
-- Generated by FFT 13.0 [Altera, IP Toolbench 1.3.0 Build 232]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2015 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;
library auk_dspip_r22sdf_lib;

ENTITY fft_64 IS
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		fftpts_in	: IN STD_LOGIC_VECTOR (6 DOWNTO 0);
		inverse	: IN STD_LOGIC;
		sink_valid	: IN STD_LOGIC;
		sink_sop	: IN STD_LOGIC;
		sink_eop	: IN STD_LOGIC;
		sink_real	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_imag	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_error	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_ready	: IN STD_LOGIC;
		fftpts_out	: OUT STD_LOGIC_VECTOR (6 DOWNTO 0);
		sink_ready	: OUT STD_LOGIC;
		source_error	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_sop	: OUT STD_LOGIC;
		source_eop	: OUT STD_LOGIC;
		source_valid	: OUT STD_LOGIC;
		source_real	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		source_imag	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0)
	);
END fft_64;

ARCHITECTURE SYN OF fft_64 IS


	COMPONENT auk_dspip_r22sdf_top_fft_130
	GENERIC (
		MAX_FFTPTS_g	: NATURAL;
		NUM_STAGES_g	: NATURAL;
		DATAWIDTH_g	: NATURAL;
		TWIDWIDTH_g	: NATURAL;
		MAX_GROW_g	: NATURAL;
		TWIDROM_BASE_g	: STRING;
		DSP_ROUNDING_g	: NATURAL;
		INPUT_FORMAT_g	: STRING;
		OUTPUT_FORMAT_g	: STRING;
		REPRESENTATION_g	: STRING;
		DSP_ARCH_g	: NATURAL;
		PRUNE_g	: STRING
	);
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		fftpts_in	: IN STD_LOGIC_VECTOR (6 DOWNTO 0);
		inverse	: IN STD_LOGIC;
		sink_valid	: IN STD_LOGIC;
		sink_sop	: IN STD_LOGIC;
		sink_eop	: IN STD_LOGIC;
		sink_real	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_imag	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_error	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_ready	: IN STD_LOGIC;
		fftpts_out	: OUT STD_LOGIC_VECTOR (6 DOWNTO 0);
		sink_ready	: OUT STD_LOGIC;
		source_error	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_sop	: OUT STD_LOGIC;
		source_eop	: OUT STD_LOGIC;
		source_valid	: OUT STD_LOGIC;
		source_real	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		source_imag	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0)
	);

	END COMPONENT;

BEGIN

	auk_dspip_r22sdf_top_fft_130_inst : auk_dspip_r22sdf_top_fft_130
	GENERIC MAP (
		MAX_FFTPTS_g => 64,
		NUM_STAGES_g => 3,
		DATAWIDTH_g => 16,
		TWIDWIDTH_g => 16,
		MAX_GROW_g => 0,
		TWIDROM_BASE_g => "fft_64_",
		DSP_ROUNDING_g => 0,
		INPUT_FORMAT_g => "NATURAL_ORDER",
		OUTPUT_FORMAT_g => "NATURAL_ORDER",
		REPRESENTATION_g => "FIXEDPT",
		DSP_ARCH_g => 0,
		PRUNE_g => "3,2,0"
	)
	PORT MAP (
		clk  =>  clk,
		reset_n  =>  reset_n,
		fftpts_in  =>  fftpts_in,
		fftpts_out  =>  fftpts_out,
		inverse  =>  inverse,
		sink_valid  =>  sink_valid,
		sink_sop  =>  sink_sop,
		sink_eop  =>  sink_eop,
		sink_real  =>  sink_real,
		sink_imag  =>  sink_imag,
		sink_ready  =>  sink_ready,
		sink_error  =>  sink_error,
		source_error  =>  source_error,
		source_ready  =>  source_ready,
		source_sop  =>  source_sop,
		source_eop  =>  source_eop,
		source_valid  =>  source_valid,
		source_real  =>  source_real,
		source_imag  =>  source_imag
	);


END SYN;


-- =========================================================
-- FFT Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, FFT Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="FFT MegaCore Function"  version="13.0"  build="232"  iptb_version="1.3.0 Build 232"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.FFTModelClass"  active_core="auk_dspip_r22sdf_top_fft_130" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "use_mem" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_type" value="M512"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DEVICE" value="Cyclone IV E"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NPS" value="64"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MPR" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "TWR" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "OPR" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ARCH" value="3"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUME" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ENGINE_THROUGHPUT" value="4"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "BFP" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MULT_TYPE" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MULT_IMP" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MEGA" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "M512" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "LOGIC_IN_RAM" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_LE" value="3657"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_M4K" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_MEGA" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_M512" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_DSP" value="24"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_CALC_CYCLES" value="128"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_BLK_THROUGHPUT_CYCLES" value="64"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs1" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs2" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs3" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfc1" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfc2" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfc3" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ENA" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_MEMBITS" value="5606"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "INPUT_ORDER" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "OUTPUT_ORDER" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "REPRESENTATION" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ENGINE_ONLY" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DSP_ARCH" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DIRECTION" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="VHDL"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enabled" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "gb_enabled" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "filename" value="fft_64.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "greybox">
-- Retrieval info:      <PRIVATE name = "filename" value="fft_64_syn.v"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP4CE115F29C7"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone IV E"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS/>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
-- RELATED_FILES: fft_64.vhd;
-- IPFS_FILES: fft_64.vho;
-- =========================================================
